### ISSUE TITLE
TypeError: can't convert String into Array when GEM_PATH is set

### ISSUE THREAD

**Issue by maxcom** [Jasig/sass-maven-plugin#47]
```
[INFO] --- sass-maven-plugin:1.1.1:update-stylesheets (default) @ lor ---
[INFO] Compiling SASS Templates
[INFO] Queing SASS Template for compile: /Users/maxcom/git-checkout/lorsource/src/main/webapp/sass => /Users/maxcom/git-checkout/lorsource/target/lor-1.0-SNAPSHOT
TypeError: can't convert String into Array
       + at org/jruby/RubyArray.java:2963
  (root) at <script>:5
org.jruby.embed.EvalFailedException: (TypeError) can't convert String into Array
    at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:136)
    at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:90)
    at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:153)
    at org.jasig.maven.plugin.sass.AbstractSassMojo.executeSassScript(AbstractSassMojo.java:191)
    at org.jasig.maven.plugin.sass.UpdateStylesheetsMojo.execute(UpdateStylesheetsMojo.java:43)
```

Here is the beginning of that script:

```
[ERROR] require 'rubygems'
[ERROR] env = { 'GEM_PATH' => [
[ERROR] '/Users/maxcom/git-checkout/lorsource/target/rubygems'
[ERROR] ] }
[ERROR] env['GEM_PATH'] += ENV['GEM_PATH'] unless ENV['GEM_PATH'].nil?
[ERROR] Gem.paths = env
```

Workaround: `unset GEM_PATH` before running mvn

**Comment by dcmoore** [comment]
+1. Looking forward to 1.1.2 as I am running into this issue.

**Comment by yegor256** [comment]
use this plugin and you'll be fine:

```xml
<plugin>
  <groupId>nl.geodienstencentrum.maven</groupId>
  <artifactId>sass-maven-plugin</artifactId>
  <version>2.5</version>
</plugin>
```

see http://www.geodienstencentrum.nl/sass-maven-plugin/update-stylesheets-mojo.html

**Comment by ChristianMurphy** [comment]
This version is no longer maintained. Refer to more recent forks at https://github.com/Jasig/sass-maven-plugin/network for more up to date versions.
